### ISSUE TITLE
自定义Chrome浏览器Video控件

### ISSUE THREAD

**Issue by Veveue** [Veveue/veveue.github.io#3]
> video隐藏下载按钮
```html
 <video controls controlsList="nodownload" src="//storage.googleapis.com/media-session/caminandes/short.mp4#t=84"></video>

```
> css处理方法
```css
/* 隐藏视频默认的下载按钮*/
video::-webkit-media-controls-enclosure {
    overflow: hidden;
}
video::-webkit-media-controls-panel {
    width: calc(100% + 5px);
}
video::-internal-media-controls-download-button {
    display: none;
}
```
[demo](http://htmlpreview.github.io/?https://github.com/googlechrome/samples/blob/gh-pages/media/controlslist.html)
